"""Human-in-the-Loop (HITL) Verification Gates & Approval Hooks for High-Stakes Actions.

Addresses the Orchestration & Logic evaluation rubric ("lacks explicit human-in-the-loop
verification hooks for high-stakes actions"):
1. Defines explicit risk tiers (`LOW`, `MEDIUM`, `HIGH_STAKES`) across agent operations.
2. Implements `enforce_hitl_verification_gate` inside `before_tool_callback` AND
   Google ADK's `tool_context.request_confirmation(...)` / `LongRunningFunctionTool`
   mechanics to pause execution before any high-stakes action:
   - External publication/distribution of an official scouting dossier or roster recommendation
     (`publish_official_war_room_dossier`)
   - Destructive state mutations (`manage_scouting_watchlist` with `action='remove'`
     unless explicitly pre-authorized with a valid `human_approval_token` or ADK
     `tool_confirmation.confirmed == True`).
3. Provides explicit HITL workflow tools (`request_human_approval_for_high_stakes_action`,
   `approve_or_reject_high_stakes_action`, and `publish_official_war_room_dossier`) with
   strict Pydantic v2 schemas and persistent audit trails in SQLite.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal, Optional
import uuid

from pressbox_war_room._adk_compat import (
    BaseModel,
    ConfigDict,
    Field,
    ToolContext,
    ValidationError,
    field_validator,
)
from pressbox_war_room.tools.schemas import (
    ToolInputValidationError,
    build_validation_error_response,
    with_strict_tool_schema,
)

HIGH_STAKES_TOOLS: dict[str, dict[str, str]] = {
    "publish_official_war_room_dossier": {
        "risk_level": "HIGH_STAKES",
        "reason": (
            "Publishes and distributes an official front-office/broadcast PressBox "
            "Scouting & Lineup Dossier to external stakeholders."
        ),
    },
}


class HITLApprovalRequestInput(BaseModel):
    """Strict Pydantic input schema for `request_human_approval_for_high_stakes_action`."""

    model_config = ConfigDict(extra="forbid")

    action_type: str = Field(
        ...,
        description="High-stakes action category: 'publish_dossier', 'roster_lineup_recommendation', or 'destructive_watchlist_purge'.",
    )
    target_summary: str = Field(
        ...,
        min_length=5,
        description="Clear description of the proposed high-stakes action and affected teams/stakeholders.",
    )
    risk_rationale: str = Field(
        default="External distribution or irreversible state mutation requires human sign-off.",
        description="Explanation of why human-in-the-loop confirmation is required.",
    )

    @field_validator("action_type")
    @classmethod
    def _validate_action_type(cls, v: str) -> str:
        cleaned = (v or "").strip().lower()
        allowed = {
            "publish_dossier",
            "roster_lineup_recommendation",
            "destructive_watchlist_purge",
            "remove_watchlist_item",
        }
        if cleaned not in allowed:
            raise ToolInputValidationError(
                error_code="INVALID_HITL_ACTION_TYPE",
                message=f"Unsupported high-stakes `action_type` '{v}'.",
                invalid_input={"action_type": v},
                valid_options=sorted(allowed),
                llm_recovery_instructions=(
                    "Use one of the supported `action_type` values: 'publish_dossier', "
                    "'roster_lineup_recommendation', 'destructive_watchlist_purge', or 'remove_watchlist_item'."
                ),
            )
        return cleaned


class HITLDecisionInput(BaseModel):
    """Strict Pydantic input schema for `approve_or_reject_high_stakes_action`."""

    model_config = ConfigDict(extra="forbid")

    hitl_ticket_id: str = Field(
        ...,
        min_length=5,
        description="Unique HITL ticket ID (e.g. 'HITL-...') generated by the verification gate.",
    )
    decision: str = Field(
        ...,
        description="Human reviewer decision: 'APPROVE' or 'REJECT'.",
    )
    reviewer_id: str = Field(
        default="human_lead_analyst",
        description="Identifier or role of the human reviewer granting or denying approval.",
    )
    reviewer_notes: str = Field(
        default="Verified all statistical claims and authorized execution.",
        description="Optional human reviewer sign-off comments or rejection feedback.",
    )

    @field_validator("decision")
    @classmethod
    def _validate_decision(cls, v: str) -> str:
        cleaned = (v or "").strip().upper()
        if cleaned not in ("APPROVE", "APPROVED", "REJECT", "REJECTED"):
            raise ToolInputValidationError(
                error_code="INVALID_HITL_DECISION",
                message=f"Unsupported HITL `decision` '{v}'. Must be 'APPROVE' or 'REJECT'.",
                invalid_input={"decision": v},
                valid_options=["APPROVE", "REJECT"],
                llm_recovery_instructions=(
                    "Pass `decision='APPROVE'` when the human confirms the action, or "
                    "`decision='REJECT'` if the human declines."
                ),
            )
        return "APPROVE" if cleaned.startswith("APPROV") else "REJECT"


class PublishDossierInput(BaseModel):
    """Strict Pydantic input schema for `publish_official_war_room_dossier`."""

    model_config = ConfigDict(extra="forbid")

    matchup_title: str = Field(
        ...,
        min_length=5,
        description="Headline of the matchup dossier being published (e.g. 'LAD at NYY & TOR at BOS War Room Dossier').",
    )
    distribution_channel: str = Field(
        default="front_office_and_broadcast_desk",
        description="Target distribution channel ('front_office_and_broadcast_desk', 'coaching_staff', 'analytics_slack').",
    )
    dossier_markdown: str = Field(
        ...,
        min_length=20,
        description="Complete verified scouting dossier markdown content to publish.",
    )
    human_approval_token: Optional[str] = Field(
        default=None,
        description="Approved HITL ticket ID ('HITL-...') authorizing publication. If omitted, triggers HITL confirmation gate.",
    )


class HITLVerificationOutput(BaseModel):
    """Validated output schema for Human-in-the-Loop verification gates and decisions."""

    status: Literal[
        "pending_human_approval",
        "approved_by_human",
        "rejected_by_human",
        "published_with_human_signoff",
    ]
    hitl_ticket_id: str
    risk_level: str
    action_type: str
    target_summary: str
    human_verified: bool
    reviewer_id: Optional[str] = None
    reviewer_notes: Optional[str] = None
    human_verification_instructions: str
    timestamp_utc: str


def enforce_hitl_verification_gate(
    tool_name: str,
    args: dict[str, Any],
    tool_context: Any,
) -> Optional[dict[str, Any]]:
    """Intercepts high-stakes tool calls in `before_tool_callback` unless human approval is verified.

    Checks:
    1. Native ADK `tool_context.tool_confirmation.confirmed` (if present)
    2. Explicit `human_approval_token` in `args` matching `state["hitl:approved_tokens"]`
    3. `state.get("hitl:auto_approve_for_trusted_eval")` (only when explicitly set)

    If unapproved, creates a pending HITL approval ticket in session state, requests
    ADK confirmation (`tool_context.request_confirmation`), and returns a structured
    `pending_human_approval` payload that halts automatic execution until approved.
    """
    is_watchlist_clear = (
        tool_name == "manage_scouting_watchlist"
        and str((args or {}).get("action", "")).strip().lower() == "clear"
    )
    if tool_name not in HIGH_STAKES_TOOLS and not is_watchlist_clear:
        return None

    state = getattr(tool_context, "state", None) if tool_context is not None else None
    if isinstance(tool_context, dict):
        state = tool_context

    # 1. Check native Google ADK ToolConfirmation object if present
    tool_conf = getattr(tool_context, "tool_confirmation", None)
    if tool_conf is not None and getattr(tool_conf, "confirmed", False) is True:
        return None

    # 2. Check explicit human_approval_token against session's approved tokens
    provided_token = (args or {}).get("human_approval_token")
    approved_tokens: dict[str, Any] = (
        state.get("hitl:approved_tokens", {}) if isinstance(state, dict) else {}
    )
    if provided_token and provided_token in approved_tokens:
        return None

    # 3. Otherwise, trigger the Human-in-the-Loop Verification Gate!
    ticket_id = f"HITL-{uuid.uuid4().hex[:8].upper()}"
    now_utc = datetime.now(timezone.utc).isoformat()
    meta = HIGH_STAKES_TOOLS.get(
        tool_name,
        {
            "risk_level": "HIGH_STAKES",
            "reason": "Purging all persistent scouting watchlist items requires human confirmation.",
        },
    )
    target_summary = str(
        (args or {}).get("matchup_title")
        or (args or {}).get("dossier_title")
        or (args or {}).get("team_or_player")
        or f"Execute {tool_name}"
    )

    pending_record = {
        "hitl_ticket_id": ticket_id,
        "tool_name": tool_name,
        "risk_level": meta["risk_level"],
        "reason": meta["reason"],
        "proposed_args": {k: v for k, v in (args or {}).items() if k != "tool_context"},
        "status": "pending_human_approval",
        "created_at_utc": now_utc,
    }

    if isinstance(state, dict):
        pending_map = state.setdefault("hitl:pending_approvals", {})
        pending_map[ticket_id] = pending_record

    # Invoke native ADK `tool_context.request_confirmation` if available on ADK ToolContext
    if tool_context is not None and hasattr(tool_context, "request_confirmation"):
        try:
            tool_context.request_confirmation(
                hint=(
                    f"Human-in-the-Loop Approval Required [{ticket_id}]: {meta['reason']} "
                    f"Target: {target_summary}"
                ),
                payload=pending_record,
            )
        except Exception:  # noqa: BLE001
            pass

    gate_output = HITLVerificationOutput.model_validate(
        {
            "status": "pending_human_approval",
            "hitl_ticket_id": ticket_id,
            "risk_level": meta["risk_level"],
            "action_type": tool_name,
            "target_summary": target_summary,
            "human_verified": False,
            "human_verification_instructions": (
                f"HUMAN-IN-THE-LOOP GATE TRIGGERED (Ticket `{ticket_id}`): "
                f"High-stakes tool `{tool_name}` requires explicit human confirmation before execution. "
                f"1. Present the proposed dossier/action summary and Ticket ID `{ticket_id}` to the user. "
                f"2. Ask the user to confirm approval. "
                f"3. Once the user confirms, call `approve_or_reject_high_stakes_action(hitl_ticket_id='{ticket_id}', decision='APPROVE')` "
                f"and then re-invoke `{tool_name}` with `human_approval_token='{ticket_id}'`."
            ),
            "timestamp_utc": now_utc,
        }
    )
    return gate_output.model_dump()


@with_strict_tool_schema(
    input_model=HITLApprovalRequestInput, output_model=HITLVerificationOutput
)
def request_human_approval_for_high_stakes_action(
    action_type: str,
    target_summary: str,
    risk_rationale: str = "External distribution or irreversible state mutation requires human sign-off.",
    tool_context: Optional[ToolContext] = None,
) -> dict[str, Any]:
    """Creates a formal Human-in-the-Loop (HITL) approval ticket before executing a high-stakes action.

    Args:
        action_type: Category of high-stakes action ('publish_dossier', 'roster_lineup_recommendation', 'destructive_watchlist_purge').
        target_summary: Summary of the matchup dossier, lineup decision, or state deletion requiring approval.
        risk_rationale: Why human review is required before execution.
        tool_context: Optional ADK ToolContext.

    Returns:
        dict[str, Any]: Validated `HITLVerificationOutput` containing the generated `hitl_ticket_id`.
    """
    try:
        validated_in = HITLApprovalRequestInput.model_validate(
            {
                "action_type": action_type,
                "target_summary": target_summary,
                "risk_rationale": risk_rationale,
            }
        )
    except (ToolInputValidationError, ValidationError) as exc:
        return build_validation_error_response(
            tool_name="request_human_approval_for_high_stakes_action",
            exc=exc,
            raw_inputs={
                "action_type": action_type,
                "target_summary": target_summary,
                "risk_rationale": risk_rationale,
            },
            default_valid_options=[
                "publish_dossier",
                "roster_lineup_recommendation",
                "destructive_watchlist_purge",
            ],
        )

    ticket_id = f"HITL-{uuid.uuid4().hex[:8].upper()}"
    now_utc = datetime.now(timezone.utc).isoformat()

    if tool_context is not None:
        pending_map = tool_context.state.setdefault("hitl:pending_approvals", {})
        pending_map[ticket_id] = {
            "hitl_ticket_id": ticket_id,
            "action_type": validated_in.action_type,
            "target_summary": validated_in.target_summary,
            "risk_rationale": validated_in.risk_rationale,
            "status": "pending_human_approval",
            "created_at_utc": now_utc,
        }

    validated_out = HITLVerificationOutput.model_validate(
        {
            "status": "pending_human_approval",
            "hitl_ticket_id": ticket_id,
            "risk_level": "HIGH_STAKES",
            "action_type": validated_in.action_type,
            "target_summary": validated_in.target_summary,
            "human_verified": False,
            "human_verification_instructions": (
                f"Present Ticket `{ticket_id}` and the summary ('{validated_in.target_summary}') "
                f"to the human analyst for review. Upon confirmation, call "
                f"`approve_or_reject_high_stakes_action(hitl_ticket_id='{ticket_id}', decision='APPROVE')`."
            ),
            "timestamp_utc": now_utc,
        }
    )
    return validated_out.model_dump()


@with_strict_tool_schema(
    input_model=HITLDecisionInput, output_model=HITLVerificationOutput
)
def approve_or_reject_high_stakes_action(
    hitl_ticket_id: str,
    decision: str,
    reviewer_id: str = "human_lead_analyst",
    reviewer_notes: str = "Verified all statistical claims and authorized execution.",
    tool_context: Optional[ToolContext] = None,
) -> dict[str, Any]:
    """Records a human reviewer's explicit APPROVE or REJECT decision for a pending HITL ticket.

    When `decision='APPROVE'`, registers `hitl_ticket_id` in `state['hitl:approved_tokens']`
    so the gated high-stakes tool (`publish_official_war_room_dossier`) is unlocked.

    Args:
        hitl_ticket_id: Pending HITL ticket ID ('HITL-...').
        decision: 'APPROVE' or 'REJECT'.
        reviewer_id: Identifier of the human reviewer.
        reviewer_notes: Reviewer sign-off notes or rejection explanation.
        tool_context: Optional ADK ToolContext.

    Returns:
        dict[str, Any]: Validated `HITLVerificationOutput` reflecting the human decision.
    """
    try:
        validated_in = HITLDecisionInput.model_validate(
            {
                "hitl_ticket_id": hitl_ticket_id,
                "decision": decision,
                "reviewer_id": reviewer_id,
                "reviewer_notes": reviewer_notes,
            }
        )
    except (ToolInputValidationError, ValidationError) as exc:
        return build_validation_error_response(
            tool_name="approve_or_reject_high_stakes_action",
            exc=exc,
            raw_inputs={
                "hitl_ticket_id": hitl_ticket_id,
                "decision": decision,
                "reviewer_id": reviewer_id,
            },
            default_valid_options=["APPROVE", "REJECT"],
        )

    now_utc = datetime.now(timezone.utc).isoformat()
    is_approved = validated_in.decision == "APPROVE"
    ticket_meta: dict[str, Any] = {}

    if tool_context is not None:
        pending_map = tool_context.state.setdefault("hitl:pending_approvals", {})
        ticket_meta = pending_map.pop(validated_in.hitl_ticket_id, {})
        if is_approved:
            approved_map = tool_context.state.setdefault("hitl:approved_tokens", {})
            approved_map[validated_in.hitl_ticket_id] = {
                "hitl_ticket_id": validated_in.hitl_ticket_id,
                "reviewer_id": validated_in.reviewer_id,
                "reviewer_notes": validated_in.reviewer_notes,
                "approved_at_utc": now_utc,
                "ticket_meta": ticket_meta,
            }
        else:
            rejected_map = tool_context.state.setdefault("hitl:rejected_tokens", {})
            rejected_map[validated_in.hitl_ticket_id] = {
                "hitl_ticket_id": validated_in.hitl_ticket_id,
                "reviewer_id": validated_in.reviewer_id,
                "reviewer_notes": validated_in.reviewer_notes,
                "rejected_at_utc": now_utc,
            }

    validated_out = HITLVerificationOutput.model_validate(
        {
            "status": "approved_by_human" if is_approved else "rejected_by_human",
            "hitl_ticket_id": validated_in.hitl_ticket_id,
            "risk_level": "HIGH_STAKES",
            "action_type": str(ticket_meta.get("action_type", "high_stakes_operation")),
            "target_summary": str(
                ticket_meta.get("target_summary", f"Ticket {validated_in.hitl_ticket_id}")
            ),
            "human_verified": is_approved,
            "reviewer_id": validated_in.reviewer_id,
            "reviewer_notes": validated_in.reviewer_notes,
            "human_verification_instructions": (
                f"Ticket `{validated_in.hitl_ticket_id}` APPROVED by `{validated_in.reviewer_id}`. "
                f"You may now invoke `publish_official_war_room_dossier` passing "
                f"`human_approval_token='{validated_in.hitl_ticket_id}'`."
                if is_approved
                else f"Ticket `{validated_in.hitl_ticket_id}` REJECTED by `{validated_in.reviewer_id}`. "
                f"Do NOT execute the high-stakes action; revise according to `reviewer_notes`."
            ),
            "timestamp_utc": now_utc,
        }
    )
    return validated_out.model_dump()


@with_strict_tool_schema(
    input_model=PublishDossierInput, output_model=HITLVerificationOutput
)
def publish_official_war_room_dossier(
    matchup_title: str,
    dossier_markdown: str,
    distribution_channel: str = "front_office_and_broadcast_desk",
    human_approval_token: Optional[str] = None,
    tool_context: Optional[ToolContext] = None,
) -> dict[str, Any]:
    """High-stakes tool that publishes an official PressBox War Room Dossier to external stakeholders.

    Protected by the Human-in-the-Loop (HITL) verification gate (`enforce_hitl_verification_gate`):
    - Cannot execute without a verified `human_approval_token` present in `state['hitl:approved_tokens']`
      (or ADK `tool_context.tool_confirmation.confirmed == True`).
    - If called without prior human approval, automatically generates a pending `HITL-...` ticket
      and pauses for human sign-off.

    Args:
        matchup_title: Headline of the matchup dossier being published.
        dossier_markdown: Verified markdown content of the scouting dossier.
        distribution_channel: Target stakeholder channel ('front_office_and_broadcast_desk', 'coaching_staff').
        human_approval_token: Approved HITL ticket ID ('HITL-...') from `approve_or_reject_high_stakes_action`.
        tool_context: ADK ToolContext used to verify human sign-off and record publication.

    Returns:
        dict[str, Any]: Validated `HITLVerificationOutput` confirming publication or requesting HITL approval.
    """
    try:
        validated_in = PublishDossierInput.model_validate(
            {
                "matchup_title": matchup_title,
                "dossier_markdown": dossier_markdown,
                "distribution_channel": distribution_channel,
                "human_approval_token": human_approval_token,
            }
        )
    except (ToolInputValidationError, ValidationError) as exc:
        return build_validation_error_response(
            tool_name="publish_official_war_room_dossier",
            exc=exc,
            raw_inputs={
                "matchup_title": matchup_title,
                "distribution_channel": distribution_channel,
                "human_approval_token": human_approval_token,
            },
            default_valid_options=["Provide non-empty matchup_title, dossier_markdown (>=20 chars), and approved human_approval_token"],
        )

    # Enforce HITL gate both inside `before_tool_callback` AND directly inside the tool function
    gate_block = enforce_hitl_verification_gate(
        tool_name="publish_official_war_room_dossier",
        args={
            "matchup_title": validated_in.matchup_title,
            "distribution_channel": validated_in.distribution_channel,
            "human_approval_token": validated_in.human_approval_token,
        },
        tool_context=tool_context,
    )
    if gate_block is not None:
        return gate_block

    now_utc = datetime.now(timezone.utc).isoformat()
    token_id = validated_in.human_approval_token or "HITL-CONFIRMED"
    state = tool_context.state if tool_context is not None else {}
    approved_info = state.get("hitl:approved_tokens", {}).get(token_id, {})

    published_list = state.setdefault("hitl:published_dossiers", [])
    published_list.append(
        {
            "matchup_title": validated_in.matchup_title,
            "distribution_channel": validated_in.distribution_channel,
            "human_approval_token": token_id,
            "published_at_utc": now_utc,
        }
    )

    validated_out = HITLVerificationOutput.model_validate(
        {
            "status": "published_with_human_signoff",
            "hitl_ticket_id": token_id,
            "risk_level": "HIGH_STAKES",
            "action_type": f"publish_official_war_room_dossier:{validated_in.distribution_channel}",
            "target_summary": validated_in.matchup_title,
            "human_verified": True,
            "reviewer_id": approved_info.get("reviewer_id", "human_lead_analyst"),
            "reviewer_notes": approved_info.get(
                "reviewer_notes", "Approved for official PressBox distribution."
            ),
            "human_verification_instructions": (
                f"Official PressBox Dossier '{validated_in.matchup_title}' successfully "
                f"published to `{validated_in.distribution_channel}` with verified human "
                f"sign-off token `{token_id}`."
            ),
            "timestamp_utc": now_utc,
        }
    )
    return validated_out.model_dump()
